kumuluzee:
  name: rso1920-video-streamer
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: streamer-endpoint
        url-pattern: /v1/stream/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="b854a7b7-ead9-432d-9dbe-720165e79cc9-ls.logit.io"
                              port="11693" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'

rest-config:
  is-service-up: true
  catalog-uri: /v1/fileMetadata